-- CREATE TABLE products (
--     id SERIAL,
--     product_name VARCHAR(255) NOT NULL,
--     price NUMERIC(10,2),
--     stock INT NOT NULL,
--     category VARCHAR(255) NOT NULL,
--     rating BIGINT 
-- )

-- INSERT INTO products (
--     product_name,
--     price,
--     stock,
--     category,
--     rating
-- )
-- VALUES (
--     'Running Shoes',
--     1500,
--     100,
--     'Sports',
--     4.5
-- ),
-- (
--     'Yoga Mat',
--     400,
--     100,
--     'Sports',
--     4.5
-- ),
-- (
--     'Bluetooth Speaker',
--     1000,
--     200,
--     'Electronics',
--     4.5
-- ),
-- (
--     'Coffee Maker',
--     1500,
--     50,
--     'Kitchen',
--     4.5
-- ),
-- (
--     'External Hard Drive',
--     3000,
--     50,
--     'Electronics',
--     4.5
-- );

-- SELECT * FROM products;

-- SELECT product_name, price FROM products;

SELECT stock FROM products;
